server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yeyeck/config-center
          searchPaths: cloudconfig
          # username:
          # password:
      label: master
